<?php

/**
  * Implements hook_menu().
  */
function ixdfail_menu() {
  $items['submit-fail']= array(
    'title' => t('Submit a Fail/WTF'),
    'page callback' => 'ixdfail_submit_fail',
    'access callback' => 'ixdfail_submit_fail_access'
  );
  return $items;
}

function ixdfail_submit_fail_access() {
  return TRUE;
}

/**
 * Menu callback for submitting Fail nodes.
 * We want a "Submit a fail" link in the main menu
 * for both authenticated and anonymous users.
 * Drupal hides menu links when a user lacks access to the destination,
 * so we use this callback instead of a link to node/add/fail.
 */
function ixdfail_submit_fail() {
  // The user is not logged in. Prompt her to register or login.
  if (user_is_anonymous()) {
    drupal_set_message(t("Please login or register to submit to @site_name :)", array('@site_name' => variable_get('site_name', 'IxD Fail'))));
    drupal_goto('user/register');
  }
  // The user is logged in. Provide the Fail creation form with
  // a slightly improved page title.
  else {
    global $user;
    $account = $user;
    drupal_set_title(t('Submit an @site_name', array('@site_name' => variable_get('site_name', 'IxD Fail'))));
    $node = new stdClass;
    $node->uid = $account->uid;
    $node->name = $account->name;
    $node->type = 'fail';
    $node->language = '';
    module_load_include('inc', 'node', 'node.pages');
    return drupal_get_form('fail_node_form', $node);
  }
}
